Repository USACE/cumulus-api, pull requests merged in 2020-12, with the labels that each got.

#36 add check to sql that both min and hour = 0
  root/models/download.go
Labels: bug

#38 Feature/packager gridinfo lowerleft xy
  async_packager/packager/dss.py
Labels: bug, enhancement

#42 Feature/productfiles seed data
  database/getProductFiles.py
  database/sql/30-seed_data.sql
  database/sql/31-seed_prodfiles.sql
  database/sql/init.sql
Labels: enhancement

#47 Feature/basin to watershed
  api/handlers/basins.go
  api/main.go
  api/models/basins.go
  api/models/download.go
  api/models/watershed.go
  async_packager/packager/dss.py
  async_packager/packager/packager.py
  database/pgadmin.sh
  database/sql/10-tables.sql
  database/sql/10a-views.sql
  database/sql/20-roles.sql
  database/sql/30-seed_data.sql
  database/sql/30a-seed_watershed.sql
  database/sql/init.sql
  database/sql/migrations/feature_downloads.sql
  database/sql/migrations/feature_product_groups.sql
  database/sql/migrations/feature_product_statistics.sql
  database/sql/migrations/product_is_fields_not_null.sql
  database/sql/migrations/user_profiles.sql
  docker-compose.yml
  tests/cumulus-regression.postman_collection.json
Labels: enhancement
